function CheckDataCountRaw(airportIcao)

%% Declaring constants and default input argument
% %Resetting MATLAB environment (for debugging)
% close;
% clear;
% clc;
% %Declaring default input arguments (for debugging as script)
% airportIcao = 'WIII';
%Reading raw data
strMetar = readcell(['../Raw Data/',airportIcao,'.txt'],'Delimiter','');
%Parsing station name and METAR data timestamp
metarStation    = ParseMetarStation(strMetar);
metarDateTime   = ParseMetarDateTime(strMetar);
%Combining all data into one table
dataMetar = table(metarStation,...
                  metarDateTime,...
                  'VariableNames',{'station',...
                                   'time'});
%Creating and adding grouping variables
groupYear  = year(dataMetar.time);
groupMonth = month(dataMetar.time);
groupDay   = day(dataMetar.time);
groupHour  = hour(dataMetar.time);
dataMetar  = [dataMetar,table(groupYear,groupMonth,groupDay,groupHour)];
dataMetar  = rmmissing(dataMetar);

%% Preparing figure and & uicontrol objects for plotting
%Declaring constants for figure creation
PAD_FIGURE  = 0.025;
AXES_HEIGHT = (1-(8*PAD_FIGURE))/2;
MENU_WIDTH  = 0.1;
%Creating figure and uicontrol
figMain    = figure('WindowState','maximized');
axOverview = axes('Parent',figMain,...
                  'Units','normalized',...
                  'Position',[PAD_FIGURE,...
                              1 - PAD_FIGURE - AXES_HEIGHT,...
                              1 - (3*PAD_FIGURE),...
                              AXES_HEIGHT],...
                  'Tag','axOverview',...
                  'XGrid','on',...
                  'YGrid','on',...
                  'ZGrid','on');
popupMonth = uicontrol('Parent',figMain,...
                       'Style','popupmenu',...
                       'String','Year',...
                       'HorizontalAlignment','left',...
                       'Units','normalized',...
                       'Position',[0.5 - (0.5*MENU_WIDTH),...
                                   1 - PAD_FIGURE - AXES_HEIGHT...
                                     - 2.5*PAD_FIGURE,...
                                   MENU_WIDTH,...
                                   0],...
                       'Tag','popupMonth',...
                       'Callback',@SelectMonthFcn);
axMonthlyC = axes('Parent',figMain,...
                  'Units','normalized',...
                  'Position',[PAD_FIGURE,...
                              PAD_FIGURE,...
                              1 - (3*PAD_FIGURE) - AXES_HEIGHT,...
                              AXES_HEIGHT + (2*PAD_FIGURE)]',...
                  'Tag','axMonthlyC',...
                  'XGrid','on',...
                  'YGrid','on',...
                  'ZGrid','on');
axMonthlyP = polaraxes('Parent',figMain,...
                       'Units','normalized',...
                       'Position',[1 - PAD_FIGURE - AXES_HEIGHT,...
                                   PAD_FIGURE,...
                                   AXES_HEIGHT,...
                                   AXES_HEIGHT]',...
                       'Tag','axMonthlyP');

%% Creating overview plot
%Aggregating METAR data table
summaryMonthly = groupsummary(dataMetar,{'groupYear','groupMonth'});
dateMonthly    = datetime(summaryMonthly.groupYear,...
                          summaryMonthly.groupMonth,...
                          1);
summaryDaily   = groupsummary(dataMetar,{'groupYear',...
                                         'groupMonth',...
                                         'groupDay'});
summaryHourly  = groupsummary(dataMetar,{'groupYear',...
                                         'groupMonth',...
                                         'groupDay',...
                                         'groupHour'});
%Creating meshgrid data for daily data count heat map
[meshMonth,~]  = meshgrid(dateMonthly,1:31);
meshCountDaily = zeros(size(meshMonth));
for id = 1:height(summaryDaily)
    idx_month = (dateMonthly == ...
                     datetime(summaryDaily.groupYear(id),...
                              summaryDaily.groupMonth(id),...
                              1));
	idx_date   = summaryDaily.groupDay(id);
    meshCountDaily(idx_date,idx_month) = summaryDaily.GroupCount(id);
end
%Generating imagesc contour plot for daily data count heat map
yyaxis(axOverview,'left');
imagesc(1:numel(dateMonthly),1:31,meshCountDaily,'Parent',axOverview);
%Adjusting color axis setting for imagesc contour plot
set(axOverview,'CLim',[0,96]);
colormap(flipud(jet));
cb1 = colorbar(axOverview,'Location','westoutside',...
                          'Ticks',0:24:96);
cb1.Label.String = 'Daily Data Count';
%Adjusting Y axis setting for imagesc contour plot
set(axOverview,'YDir','normal');
yticks(axOverview,0:31);
yticklabels(axOverview,0:31);
ylabel(axOverview,'Calendar Date');
%Adjusting X axis setting for imagesc contour plot
tickLabel = cell(size(dateMonthly));
for id = 1:numel(dateMonthly)
    if (month(dateMonthly(id)) == 1)||(month(dateMonthly(id)) == 7)
        tickLabel{id} = datestr(dateMonthly(id),'yyyy-mm');
    end
end
xticks(axOverview,1:numel(dateMonthly));
xticklabels(axOverview,tickLabel);
xtickangle(axOverview,90);
%Generating data count line plot
yyaxis(axOverview,'right');
plot(summaryMonthly.GroupCount,'Parent',axOverview,...
                               'LineWidth',2);
%Adjusting Y axis setting for line plot
ylim(axOverview,[floor(min(summaryMonthly.GroupCount)/240)*240,...
                 ceil(max(summaryMonthly.GroupCount)/240)*240]);
yticks(axOverview,floor(min(summaryMonthly.GroupCount)/240)*240:...
                  240:...
                  ceil(max(summaryMonthly.GroupCount)/240)*240);
ylabel(axOverview,'Monthly Data Count');
%Adding axes title
title(axOverview,['Monthly & Daily Data Count Heat Map for ',airportIcao]);

%% Creating monthly plot
%Updating month selection popup
set(popupMonth,'String',datestr(dateMonthly,'yyyy-mm'));
%Updating
SelectMonthFcn(popupMonth)

%% Declaring callback functions
function SelectMonthFcn(src,event)
    %Slicing data from selected month in popupmenu
    currentYear  = year(dateMonthly(src.Value));
    currentMonth = month(dateMonthly(src.Value));
    currentSummaryDaily = ...
        summaryDaily((summaryDaily.groupYear == currentYear) & ...
                     (summaryDaily.groupMonth == currentMonth),...
                     :);
	currentSummaryHourly = ...
        summaryHourly((summaryHourly.groupYear == currentYear) & ...
                      (summaryHourly.groupMonth == currentMonth),...
                      :);
	%Creating meshgrid data for hourly data count heat map
    [meshDay,~] = meshgrid(1:31,1:24);
    meshCountHourly    = zeros(size(meshDay));
    for id_n = 1:height(currentSummaryHourly)
        idx_hour = currentSummaryHourly.groupHour(id_n)+1;
        idx_day  = currentSummaryHourly.groupDay(id_n);
        meshCountHourly(idx_hour,idx_day) = ...
            currentSummaryHourly.GroupCount(id_n);
    end
    %Generating imagesc contour plot for hourly data count heat map
    yyaxis(axMonthlyC,'left');
    imagesc(1:31,0:23,meshCountHourly,'Parent',axMonthlyC);
    %Adjusting color axis setting for imagesc contour plot
    set(axMonthlyC,'CLim',[0,4]);
    colormap(flipud(jet));
    cb2 = colorbar(axMonthlyC,'Location','westoutside',...
                              'Ticks',0:4);
    cb2.Label.String = 'Daily Data Count';
    %Adjusting Y axis setting for imagesc contour plot
    set(axMonthlyC,'YDir','normal');
    yticks(axMonthlyC,0:23);
    yticklabels(axMonthlyC,0:23);
    ylabel(axMonthlyC,'Hour');
    %Adjusting X axis setting for imagesc contour plot
    xticks(axMonthlyC,1:31);
    xticklabels(axMonthlyC,1:31);
    %Generating data count line plot
    yyaxis(axMonthlyC,'right');
    plot(currentSummaryDaily.groupDay,currentSummaryDaily.GroupCount,...
         'Parent',axMonthlyC,...
         'LineWidth',2);
    %Adjusting Y axis setting for line plot
    ylim(axMonthlyC,[floor(min(currentSummaryDaily.GroupCount)/12)*12,...
                     ceil(max(currentSummaryDaily.GroupCount)/12)*12]);
    yticks(axMonthlyC,floor(min(currentSummaryDaily.GroupCount)/12)*12:...
                      12:...
                      ceil(max(currentSummaryDaily.GroupCount)/12)*12);
    ylabel(axMonthlyC,'Daily Data Count');
    %Adding axes title
    title(axMonthlyC,['Daily & Hourly Data Count Heat Map for ',...
                      airportIcao]);
    %Generating polar plot for hourly data count heat map
    polarplot((0:12)*pi/6,...
              [sum(meshCountHourly(1:12,:)'),...
               sum(meshCountHourly(1,:))],...
              'Parent',axMonthlyP);
	hold(axMonthlyP,'on');
	polarplot((0:12)*pi/6,...
              [sum(meshCountHourly(13:24,:)'),...
               sum(meshCountHourly(13,:))],...
              'Parent',axMonthlyP);
    hold(axMonthlyP,'off');
    %Adjusting theta axis setting for line plot
	set(axMonthlyP,'ThetaZeroLocation','top',...
                   'ThetaDir','clockwise');
	thetaticks(axMonthlyP,0:30:360);
    thetaticklabels(axMonthlyP,[12,1:11]);
    %Adjusting theta axis setting for line plot
    rlim(axMonthlyP,...
         [0,...
          ceil(max(sum(meshCountHourly(1:23,:)'))/12)*12]);
	rticks(axMonthlyP,...
           0:...
           12:...
           ceil(max(sum(meshCountHourly(1:23,:)'))/12)*12);
    legend({'AM','PM'});
    %Adding axes title
	title(axMonthlyP,['Monthly Hour-in-Day Data Count for ',airportIcao]);
end

end